--- # block separator
- hosts: all
  become: true
  become_user: root
  tasks:
    - name: "install timezone"
      apk: 
        name: tzdata
        state: present
    - name: "copy timezone filer"
      command: cp -p /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
      args:
        creates: /etc/localtime/Tokyo
- hosts: ovs
  become: true
  become_user: root
  tasks:
    - name: "ovs install"
      apk:
        name: openvswitch
        state: present
        update_cache: yes
    - service:
        name: ovs-modules
        enabled: yes
        state: started
    - service:
        name: ovsdb-server
        enabled: yes
        state: started
    - service:
        name: ovs-vswitchd
        enabled: yes
        state: started
- hosts: odl
  become: true
  become_user: root
  tasks:
    - name: install gnutar
      apk:
        name: tar
        state: present
        update_cache: yes
    - name: jdk installation
      apk:
        name: openjdk8
        state: present
        update_cache: yes
    - file:
       name: /opt
       state: directory
    - name: untar karaf
      unarchive:
        src: https://nexus.opendaylight.org/content/repositories/public/org/opendaylight/integration/karaf/0.7.3/karaf-0.7.3.tar.gz
        dest: /opt
        remote_src: yes
        owner: vagrant
        mode: 0766
        creates: /opt/karaf-0.7.3


